import 'package:flutter/material.dart';
import 'package:flutterapp/bakeryapp/generatedgroup15widget/generated/GeneratedUIDesignWidget.dart';

/* Group Group 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 800.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 800.0,
              child: GeneratedUIDesignWidget(),
            )
          ]),
    ));
  }
}
